# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Montask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Montask
  pod 'Kingfisher', '~> 4.2'
  pod 'KeychainSwift', '~> 9.0'

  target 'MontaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MontaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
